### ISSUE TITLE
Not able to get it working

### ISSUE THREAD

**Issue by mikecrittenden** [bradlc/vscode-tailwindcss#1]
Hey there, this looks awesome, I saw it from you posting it in the Tailwind slack!

So far I'm unable to get it working. In my case, my tailwind.js is in `web/themes/custom/theme/tailwind.js` and I'm testing using various `filename.html.twig` files inside `web/themes/custom/theme/templates` and it just doesn't seem to be doing anything. I don't see any autocomplete popup when typing class names. 

I tried renaming the file to `filename.twig` or even `filename.html` (even though Twig seems to be supported, looking at https://github.com/bradlc/vscode-tailwindcss/blob/master/src/extension.ts#L18) just in case and that didn't help. None of them give me any kind of autocomplete for classes. 

Any thoughts on what I could be missing? Or any info I could provide to help debug?

Thanks!

**Comment by bradlc** [comment]
Hey! Thanks for creating an issue.

Looks like this was because the extension was only looking in the workspace root for the config file. I have pushed a fix in `0.1.2` – let me know if you still have issues

**Comment by bradlc** [comment]
I’ll close this issue but feel free to reopen if needed

**Comment by mikecrittenden** [comment]
@bradlc Sadly that didn't seem to do it for me. I confirmed that I updated to 0.1.2 and restarted VS Code a couple times to be safe. Let me know if you have any other ideas or info I could provide to be helpful.

(I'm unable to reopen this issue and it's possible that it's just a quirky edge case with my particular setup anyway)

**Comment by bradlc** [comment]
Ah sorry I thought you could; I’ll reopen.

Are you using a multi-root workspace in VS Code?

**Comment by mikecrittenden** [comment]
No I'm not using multi-root, but I think the issue may be that my `node_modules` actually lives in `web/themes/custom/theme` rather than at the project root. (It's a Drupal project and the Drupal theme is where the node_modules live rather than in the project root). It seems like that may mess this up: https://github.com/bradlc/vscode-tailwindcss/blob/master/src/extension.ts#L71

So I'm not sure if that's the kind of use case you want to support. Seems like it may be tough to dynamically find the tailwindcss node module regardless of where it lives in the project, unless you make that a configurable option or something. Feel free to re-close this as wontfix if you'd like!

**Comment by bradlc** [comment]
Aah I see. Yeah if your `node_modules` isn’t in the root it won’t work currently. It uses the actual version of `tailwindcss` that you have installed.

I see two ways to solve this:

* we look for `**/node_modules` instead
* we fall back to the latest version of `tailwindcss` if we can’t find it at the root

What do you think?

**Comment by mikecrittenden** [comment]
Option 1 seems preferable to me just to be sure that versions match up, and hopefully that would be simpler to implement?

**Comment by bradlc** [comment]
I guess the "proper" solution is to support multiple Tailwind versions/configs in a single project:

* `web/themes/foo`
  * `src`
    * `index.html`
  * `node_modules`
    * `tailwindcss`
  * `tailwind.js`
* `web/themes/bar`
  * `src`
    * `index.html`
  * `node_modules`
    * `tailwindcss`
  * `tailwind.js`

Which should be doable 🤔

**Comment by mikecrittenden** [comment]
Yeah I thought about that but didn't want to push my luck :D 

I can see how that would be necessary if you have a project with multiple themes in the same codebase.

**Comment by mikecrittenden** [comment]
@bradlc you are a hero, it works like a champ now!

**Comment by theMosaad** [comment]
This problem was reintroduced again in v0.3.0. I'm running v0.2.0 for the class suggestions to show up in a workspace where node_modules isn't in the root.

**Comment by lkruselarsen** [comment]
I am experiencing this issue in v0.5.0 v0.2.0 v0.1.4 
maybe i am doing something else wrong. Tailwind is working in my project through

**Comment by TouseefQ** [comment]
I am experiencing the same issue with the Tailwind CSS IntelliSense extension in VSCode. I am using Tailwind with Wordpress. The extension was working fine before I merged everything with Wordpress but now it seems to be not working. Tailwind is working perfectly fine. Any suggestions on how we can fix the working of this extension (Tailwind CSS IntelliSense)?

**Comment by lkruselarsen** [comment]
so i created a new project from scratch, where i installed tailwindcss, postcss-cli and autoprefixer again. Only difference was that i had intellisense installed before project creation. now it works perfectly. no clue what was wrong first time around.

**Comment by pjayme** [comment]
The feature is working fine for .HTML files but have had no luck when trying to configure includeLanguages for a .ss (Silverstripe) template file. Have others had any luck with custom template languages?

**Comment by TouseefQ** [comment]
### This solved my problem:

I deleted the package-lock.json file and the node_module folder and re-installed npm in my project. The tailwind IntelliSence extension for VSCode started working after this.

**Comment by TouseefQ** [comment]
> I am experiencing the same issue with the Tailwind CSS IntelliSense extension in VSCode. I am using Tailwind with Wordpress. The extension was working fine before I merged everything with Wordpress but now it seems to be not working. Tailwind is working perfectly fine. Any suggestions on how we can fix the working of this extension (Tailwind CSS IntelliSense)?

### This solved my problem:

I deleted the package-lock.json file and the node_module folder and re-installed npm in my project. The tailwind IntelliSence extension for VSCode started working after this.
