### ISSUE TITLE
Add support for prefix

### ISSUE THREAD

**Issue by hadefication** [bradlc/vscode-tailwindcss#104]
If `prefix` is provided in the config, it should respect the said prefix in the generated classes that shows in the IntelliSense menu.

**Comment by bradlc** [comment]
Hey @hadefication. The `prefix` option is supported. Please could you confirm whether the extension works for you if you remove that option and reload your VS Code window?

**Comment by hadefication** [comment]
@bradlc, I can confirm that is working. Apparently multiple TailwindCSS in my project, one in the root and another one in the sub-directory and I'm working on the sub-directory one. It seems like the config that is using is the root one.
