### ISSUE TITLE
Not working on my Ubuntu 20.04 machine

### ISSUE THREAD

**Issue by pavangayakwad** [bradlc/vscode-tailwindcss#107]
Not working on my VSCode (with your extension) installed on Linux Ubuntu 20.04 machine. 

![image](https://user-images.githubusercontent.com/1834890/79774722-d2792b00-8350-11ea-86f3-ce191fb7f670.png)

**Comment by azrahn** [comment]
Do you have a tailwind.config.js in your root?

**Comment by pavangayakwad** [comment]
Not really, but i have postcss.config and my angular apps is working fine with my current setup. 

![image](https://user-images.githubusercontent.com/1834890/79775834-73b4b100-8352-11ea-8c63-ae9ce7be41c3.png)

**Comment by pavangayakwad** [comment]
I did tried putting one tailwind.config.js file and tested it, no luck.

![image](https://user-images.githubusercontent.com/1834890/79776244-1705c600-8353-11ea-84e3-71589423beb4.png)

**Comment by azrahn** [comment]
can you try it with a full tailwind.config.js. 
That was the solution for me.
Im using purgecss anyway so it doesn't matter its loaded.

my default config is
`module.exports = {
    theme: {
        extend: {
            
        }
    },
    variants: {},
    plugins: []
}`

**Comment by pavangayakwad** [comment]
You are right, after putting the default config 
`module.exports = { theme: { extend: { } }, variants: {}, plugins: [] }`

the intellisense started working. Thanks. It would be nice if the extension work without the dependency of this config.js file. 

![image](https://user-images.githubusercontent.com/1834890/79800713-58f63280-837a-11ea-9b4b-d3acd368a681.png)
