### ISSUE TITLE
Not working with vue cli and taiwindcss

### ISSUE THREAD

**Issue by tjinewpro** [bradlc/vscode-tailwindcss#108]
I've installed Tailwind CSS IntelliSense
but it doesn't work .. 
Is there anyone how figure this out?

**Comment by itpropro** [comment]
It seems like there are multiple bugs with the current Tailwindcss version, but @bradlc is already working on the next alpha, so we just have to give him some time :)

**Comment by itpropro** [comment]
The current alpha doesn't fix this for the newest version of nuxt/tailwindcss which implements tailwindcss 1.4.

**Comment by bradlc** [comment]
Hey @tjinewpro. Please could you try out the new version of the extension and see if that fixes your issue? Also please check the extension [requirements](https://github.com/bradlc/vscode-tailwindcss#requirements). If you're still having issues feel free to open a new issue, perhaps with a link to your project if possible.
