### ISSUE TITLE
Support new Razor file type

### ISSUE THREAD

**Issue by attilah** [bradlc/vscode-tailwindcss#109]
In VS Code if you start an ASP.NET Core 3.1 project or a Blazor project, the filetype now is "aspnetcorerazor", not "razor".

It would be nice to have support for it.

**Comment by bradlc** [comment]
This was added in [`v0.3.0-alpha.1`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.1) and will be released soon

**Comment by zolrath** [comment]
@bradlc As a heads up `aspnetcorerazor` is still missing from the languages in `v0.3.0-alpha.2`

**Comment by bradlc** [comment]
@zolrath Is that with one of the alpha releases? That directory structure should be fine in those. And is it the same after reloading the VS Code window?

**Comment by zolrath** [comment]
@bradlc Hm after a reload of VS Code it's picking up the tailwind styles, I wonder why it wasn't appearing earlier.
