### ISSUE TITLE
Poor Instruction - IntelliSense Not Working

### ISSUE THREAD

**Issue by surjithctly** [bradlc/vscode-tailwindcss#115]
I'm using simple HTML and added tailwind.min.css in my /css folder. Not using NPM or node modules. I don't know how to make it working. I'm ready to follow npm instruction if needed, but none provided. 

I also tried installing NPM myself, but not working. Another fact is other intellisense like Bootstrap working fine without any need for NPM.

I read few issues, but not able to fix it.  

Please help.

**Comment by cloonix** [comment]
You're mixing some conecepts and i don't really understand your problem. Tailwind is not like Bootstrap. In my understanding you can use a pre-compiled CSS (that min.css), but it's far away from the feature set tailwind provides. 

What issues do you read?

Maybe this answer to a similar question helps you: https://github.com/tailwindcss/discuss/issues/16#issuecomment-341502137

**Comment by surjithctly** [comment]
@cloonix may be I missed to say the word "IntelliSense" 
Tailwind is working fine, but I was trying to install "Tailwind CSS Intellisense" from VS Code. Then after I type class name, nothing works, Also tried Ctrl + Space. Restarted VS Code, but no luck. 

Anyway, When I turned on my machine aka after restart, It worked fine. 

So this issue is closed. But may be you can provide more instruction on the requrements to make this working. need to specify it should work with CDN link as Tailwind or need NPM?

I wait for your reply and you may close this issue. 

~Surjith

**Comment by mickaelchanrion** [comment]
@surjithctly, please note that for this plugin to work you need to:
- have a tailwind config file in your project
- the node module tailwindcss installed in your project

I guess this is required for performance purposes. You don't want to have the server of this plugin running for a project that doesn't use tailwind.
Take a look at this #74

**Comment by surjithctly** [comment]
I see @mickaelchanrion  So please update the readme for newbies like me. It is really frustrating.

**Comment by bradlc** [comment]
The readme has been updated thanks to @ledenis 🙌
