### ISSUE TITLE
`@apply` not recognized working as expected

### ISSUE THREAD

**Issue by Rawnly** [bradlc/vscode-tailwindcss#117]
### The Problem
Apply syntax not recognized from `vs-code` with multiple classes

I got:
`semi-colon expectedcss(css-semicolonexpected)`

with just: 
```css
.bodyText {
	@apply text-xl container; /* this is just an example... */
}
```

![CleanShot 2020-05-15 at 13 08 11](https://user-images.githubusercontent.com/16429579/82044179-27d4fd80-96ad-11ea-88fb-3eef197526ba.png)

**Comment by jaaneh** [comment]
Have you set up stylelint to work with Tailwind? There's an excellent written tutorial here https://www.meidev.co/blog/visual-studio-code-css-linting-with-tailwind/

**Comment by Rawnly** [comment]
Thanks that fixed the problem!

**Comment by vesper8** [comment]
I followed the above tutorial and it did fix many issues, but one issue that persists is that it is incorrectly highlighting when I have multiple `@screen` directives

See image:
<img width="474" alt="Screen Shot 2020-07-08 at 5 53 46 PM" src="https://user-images.githubusercontent.com/816028/86934154-5c8f8f00-c109-11ea-8a80-c990f772b79b.png">


Any ideas on how to resolve this improper highlighting?

**Comment by jaaneh** [comment]
@vesper8 Try adding semicolons at the end of each CSS rule. I had a similar issue with stylelint as well.
```css
@screen md {
    .footer-section {
        /* Notice the added semicolon at the end. */
        @apply tw-px-0;
    }
}
```
You're missing these inside your `md` and `lg` rules. Let me know if that helps!

**Comment by vesper8** [comment]
ah yes thank you that did the trick, actually running a "format document" cleared everything up for me.. perfect!
