### ISSUE TITLE
IntelliSense not works for Typescript

### ISSUE THREAD

**Issue by gkn06** [bradlc/vscode-tailwindcss#118]
How to make it work for .ts files?

I think `typescript `should be added here
https://github.com/bradlc/vscode-tailwindcss/blob/f5dfe02f74ac9bd68529f1997ae875691b819833/src/index.ts#L34-L39

**Comment by gkn06** [comment]
tried alpha version too with this setting but still no luck

```json
 "tailwindCSS.includeLanguages": {
    "plaintext": "typescript"
  }
```

**Comment by bradlc** [comment]
Thanks, I'll add it!

Your `includeLanguages` setting should look like this by the way:

```
"tailwindCSS.includeLanguages": {
  "typescript": "javascript"
}
```

**Comment by gkn06** [comment]
Thanks @bradlc

**Comment by tobkle** [comment]
For Typescript React I need this in the settings:
```javascript
"tailwindCSS.includeLanguages": {
    "typescript": "javascript",
    "typescriptreact": "javascript"
}
```
