### ISSUE TITLE
space-* not available

### ISSUE THREAD

**Issue by luisrudge** [bradlc/vscode-tailwindcss#119]
I'm not sure how the language server works. If we need to update with new classes manually or not etc, so I just want to report that the newly released space-* classes are not working:
![image](https://user-images.githubusercontent.com/941075/82158493-a329e100-985e-11ea-8bef-029e4791f3e3.png)

If I can help, let me know

**Comment by bradlc** [comment]
Just shipped `v0.3.0` and the space utilities should work in that version 🎉
