### ISSUE TITLE
Support for [%tw "..."] auto-completion

### ISSUE THREAD

**Issue by dylanirlbeck** [bradlc/vscode-tailwindcss#120]
Hello there! I recently created a ReasonML ppx extension ([tailwind-ppx](https://github.com/dylanirlbeck/tailwind-ppx)) that validates your Tailwind classes, and I'm wondering if there's any way that auto-completion support can be added for `vscode-tailwindcss`? In short, the PPX is used like this:

```reason
<Component className=[%tw "..."] />
```

so in VSCode, you should get auto-completion after typing in `[%tw "`.

I'm thinking we just need to tweak whatever regex you use to prompt for auto-completion, but I'm not seeing the place in the code where this can be done. I've already added support for the ppx in [`coc-tailwindcss`](https://github.com/iamcco/coc-tailwindcss), so I'm hoping it won't be too difficult to do the same with `vscode-tailwindcss`.

I'd be happy to help if necessary! Thanks in advance

**Comment by iamcco** [comment]
The language server of next version is open source now. https://github.com/bradlc/vscode-tailwindcss/tree/next

@bradlc 
What do you think of making this like an option so that uses can define their own regex.

**Comment by bradlc** [comment]
Hey @dylanirlbeck. I have created a new issue (#129) to consolidate similar requests. Please refer to that issue for comments/updates
