### ISSUE TITLE
Register custom file extension

### ISSUE THREAD

**Issue by gradinarot** [bradlc/vscode-tailwindcss#121]
How can we register a custom extension. For example I want to get IntelliSense in *.gohtml which is basically hetml file.

**Comment by bradlc** [comment]
Hey @gradinarot. There's no way to do this in the current marketplace release, but you can do it in [`v0.3.0-alpha.2`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.2):

```
"tailwindCSS.includeLanguages": {
  "gohtml": "html"
}
```

The keys in the `includeLanguages` setting are **language IDs**, not file extensions. Here are the IDs for the extensions I could find:

`casualjim.gotemplate`: `gohtml`
`dunstontc.vscode-go-syntax`: `GoHTML`
