### ISSUE TITLE
Support for tailwind.macro in styled/emotion like tw`...` or tw.div`...`

### ISSUE THREAD

**Issue by tobkle** [bradlc/vscode-tailwindcss#123]
Tried to adjust the regex in getClassNameAtPosition.ts 
in line 15 and 24 with the following pattern ...
```js
(\bclass(Name)?=[`'"][^`'"]+)|(\btw([.a-zA-Z]*)?[`'"][^`'"]+)
```
...but the search logic is obviously more sophisticated, so that didn't work.
Any suggestions?

**Comment by bradlc** [comment]
Hey @tobkle. I have created a new issue (#129) to consolidate similar requests. Please refer to that issue for comments/updates
