### ISSUE TITLE
working with other editors

### ISSUE THREAD

**Issue by gour** [bradlc/vscode-tailwindcss#126]
Hello,

just curious what would be required to make this extension working with other editors (Emacs, ST, vim...) which have support for LSP?

**Comment by bradlc** [comment]
Hey @gour. I think it depends on the editor, but generally the language service is portable and could totally be used outside of VS Code. I am not familiar with vim but there's [coc-tailwindcss](https://github.com/iamcco/coc-tailwindcss) which looks like it uses an old version of the VS Code language service.

I would like to publish the language service as its own package at some point, which would make other integrations easier.
