### ISSUE TITLE
*.scss files support?

### ISSUE THREAD

**Issue by greegus** [bradlc/vscode-tailwindcss#13]
Looking into extension's configuration files `tailwind.tmLanguage.json` seems that `.scss` files should be supported. However, `@apply` and `@tailwind` commands ale not recognized by editor within them (and highligted as an error). Tailwind autocomplete is also not available. `.css` files work just fine.

If `.scss` files are not currently supported afterall pls consider this a feature request.

![image](https://user-images.githubusercontent.com/11144945/47229129-41c23780-d3c7-11e8-8848-5975e0bcebb1.png)

- Extension Name: vscode-tailwindcss
- Extension Version: 0.1.12
- OS Version: Darwin x64 18.0.0
- VSCode version: 1.28.2

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 258,
		"activateCallTime": 0,
		"activateResolvedTime": 1315,
		"activationEvent": "workspaceContains:**/{tailwind,tailwind.config,tailwind-config,.tailwindrc}.js"
	}
}
```

**Comment by bradlc** [comment]
Hey @greegus 

SCSS is supported. The grammar only affects syntax highlighting. As far as I’m aware there is no way for an extension to extend the (S)CSS **linter**. You can disable it by setting `scss.validate` to `false`.

Regarding the autocomplete, it should work if it’s working in CSS files. Do `@screen` or `config()` suggestions appear?

**Comment by bradlc** [comment]
If you’re using [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) there is a separate setting, `vetur.validation.style`

**Comment by MpMeetPatel** [comment]
I use one trick , instead of scss/sass use css for "select languege mode"-
you'll get CSS style hinting as well as linter will not complain about for @apply @tailwing etc.

Currently No solution out there for scss so hope it'll get the **JOB DONE**

**Comment by alexcroox** [comment]
Does anyone have a workaround that doesn't involve disabling validation, which I find useful.

**Comment by hacknug** [comment]
Disable default validation for these and use Stylelint with your own config.

**Comment by chanmathew** [comment]
> Does anyone have a workaround that doesn't involve disabling validation, which I find useful.

Follow this guide here:
https://www.meidev.co/blog/visual-studio-code-css-linting-with-tailwind/

And disable validation for .scss as well in VS code if you are using Scss files. Stylelint will handle it for you.
