### ISSUE TITLE
Add support to template in Vue files

### ISSUE THREAD

**Issue by skegel13** [bradlc/vscode-tailwindcss#14]
Is it possible to have this work in the template (html) section of .vue files?

**Comment by bradlc** [comment]
Hey @skegel13

This is already supported. Do suggestions appear for you when editing a HTML file in the same workspace?

**Comment by skegel13** [comment]
Looks like it is working now, not sure what was going on.

**Comment by CharlesOkwuagwu** [comment]
> Hey @skegel13
> 
> This is already supported. Do suggestions appear for you when editing a HTML file in the same workspace?

Hi, i have this issues with work-spaces, the IntelliSense does not come up.
