### ISSUE TITLE
Syntax highlighting in Vue <style> blocks

### ISSUE THREAD

**Issue by bradlc** [bradlc/vscode-tailwindcss#15]

**Comment by natedunn** [comment]
About to raise a glass to this issue for its first birthday. 🍻 Cheers.

**Comment by hacknug** [comment]
What's the issue here? Using `mhmadhamster.postcss-language` and `octref.vetur` without any issues (maybe some other extension too), just make sure you set the lang like this: `<style lang="postcss">`

**Comment by bradlc** [comment]
Fixed in [`v0.3.0-alpha.1`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.1) 🎉
