### ISSUE TITLE
Support for .leaf files

### ISSUE THREAD

**Issue by Coupz** [bradlc/vscode-tailwindcss#16]
First, thank you for this awesome extension.

Could you add support for .leaf files, which are used for templates in Vapor applications? 
https://github.com/vapor/leaf

If I rename a .leaf file to .html, everything works as expected.

Thank you 👍

**Comment by bradlc** [comment]
Hey @Coupz, thanks for the suggestion, this has been added in `0.1.15` – it might take a short while for the update to show up

**Comment by Coupz** [comment]
Thank you, but, well, doesn't seem to work as expected. I changed the filetype on the bottom right corner of VSCode to HTML and only getting already used classes.
If the filetype is on Leaf, I don't get any autocompletion suggestions from tailwind classes 🤔

**Comment by bradlc** [comment]
Hmm, that’s strange. All good on my end. Is that the same project that was previously working for HTML files?

**Comment by Coupz** [comment]
It's the same master.leaf file.

This is the file: 
<img width="858" alt="screenshot 2018-11-02 at 14 54 12" src="https://user-images.githubusercontent.com/1399474/47919250-35ea7100-deaf-11e8-8a57-575cd30f7d84.png"> 
The autocomplete only shadows when doing CTRL + Space on macOS Mojave.

This is the same file, just renamed the extension to .html:
<img width="827" alt="screenshot 2018-11-02 at 14 53 44" src="https://user-images.githubusercontent.com/1399474/47919316-5e726b00-deaf-11e8-8d82-15dd8ed2b23d.png">
Showing only tailwind classes that have been used before.

Really strange 🤔

**Comment by bradlc** [comment]
Ah I think I see the issue. You need to be using Tailwind CSS locally. Specifically, you need to have a config file (e.g. `tailwind.js`) and `tailwindcss` installed via npm/yarn (i.e. `node_modules/tailwindcss`)

I could probably make this clearer in the readme

**Comment by Coupz** [comment]
Alright, I'll try that with the npm/yarn package. Thank you 👍
