### ISSUE TITLE
Make tailwind.css configurable?

### ISSUE THREAD

**Issue by brasilikum** [bradlc/vscode-tailwindcss#2]
Thank you for this awesome plugin!

Reading #1 I already found out why it does not work for me:

I use an ember plugin, which stores tailwind in a particular location and also splits the config file in multiple files.

Do you need the .js to make this work, or would the output location of the compiled css be enough? In this case, if you could make this location configurable that would help me a lot!

The css intellisense plugin works fairly well for me but does not properly detect `sm:`, `active:` and so on

**Comment by bradlc** [comment]
Hey 👋

I’m not sure I fully understand your set up. When you say that Tailwind is "a particular location,"
 is that location somewhere outside of your project?

**Comment by brasilikum** [comment]
It is in fact in the project folder, in this case under frontend/app/tailwind/config/tailwind.js which includes js files in the same folder.

Should that be working out of the box?

**Comment by bradlc** [comment]
Yeah should do. And the `tailwindcss` module exists somewhere as well, in a `node_modules` directory?

It’s also worth noting that (at least for now) you must be using the default seperator (`:`) in your config.
