### ISSUE TITLE
Auto Opens Suggestions in TSX

### ISSUE THREAD

**Issue by leobauza** [bradlc/vscode-tailwindcss#22]
The default behaviour of the suggestions in TSX is to open when you start typing. For some reason when I enable `vscode-tailwindcss` the suggestions open immediately and are missing the props for my React components. On the attached gif I am showing how it automatically opens the suggestions with missing props. Then I hit `esc` and then `ctrl+space` to open the suggestions again and my props are there.

![vscode-tailwindcss-bug](https://user-images.githubusercontent.com/1823027/50308955-ec5be280-046a-11e9-94d6-b09b93f4eab9.gif)

I think ideally it would auto-open with the props there. Or if an option in the config could be added to disabled the automatic opening.

This extension is the reason I switched to VSCode, and I love it, so thanks for making it. For now I can work around the issue with just a couple extra keystrokes.

**Comment by bradlc** [comment]
Hey @leobauza 

A couple of people have brought this up now and I have started noticing it as well. The autocomplete behaviour will be changing in a upcoming release, which will prevent this from happening.

**Comment by bradlc** [comment]
This seems fine now. I think in the end it was actually a bug with VS Code.
