### ISSUE TITLE
Autocomplete @apply classes without prepending with a dot

### ISSUE THREAD

**Issue by nicooprat** [bradlc/vscode-tailwindcss#28]
Hi there,

Many thanks for this time-saving extension.

Why does it prepend autocompleted classes with a dot although it's not required [according to the docs](https://tailwindcss.com/docs/functions-and-directives/#apply)? Is it done on purpose? Could we have an option to disable it?

Current output:
```css
.btn {
  @apply .font-bold .py-2 .px-4 .rounded;
}
```

Expected output:
```css
.btn {
  @apply font-bold py-2 px-4 rounded;
}
```

Thanks!

**Comment by bradlc** [comment]
Hey @nicooprat, this sounds like a bug, sorry about that. I will ship a fix with the upcoming release which adds support for Tailwind v1

**Comment by allaire** [comment]
That would be great :) Thanks, very useful integration !

**Comment by bradlc** [comment]
The dot is gone in `0.2.0`!
