### ISSUE TITLE
Add option to disable the extension for defined languages

### ISSUE THREAD

**Issue by guillaumebriday** [bradlc/vscode-tailwindcss#3]
Hey ! First thank you for your extension.

What I mean in the title is for example : 
```json
"[markdown]": {
  "tailwind.enabled": false,
},
```
Because of this :

![screen shot 2018-08-23 at 00 21 22](https://user-images.githubusercontent.com/8252238/44494016-82712f00-a66a-11e8-8eca-56a8bd617995.png)

Thank you in advance

**Comment by bradlc** [comment]
👋 This is definitely not ideal, and something I want to improve.

I’m not sure an enable/disable option is the right solution though, as you'll still get this issue in file types which you have enabled. I this this issue can be solved by tightening up the conditions under which the suggestions are triggered.

I will work on this later today or tomorrow and let you know

**Comment by bradlc** [comment]
This should be a lot better now, in `0.1.7`

It’s a bit smarter, so things like your example ("this is a demo.") won’t trigger the suggestions.

**Comment by guillaumebriday** [comment]
I'll give it a shot !

Thanks for your work ! 👍
