### ISSUE TITLE
Not working with tailwindcss@1.0.0-beta.x

### ISSUE THREAD

**Issue by CinKon** [bradlc/vscode-tailwindcss#34]
Unfortunately I get no suggesstions since I updated tailwindcss to 1.0.0-beta.3

**Comment by bradlc** [comment]
Hey @CinKon. The extension does not currently support v1. My plan is to release a version with support before the final v1 release.

**Comment by geabenitez** [comment]
> Hey @CinKon. The extension does not currently support v1. My plan is to release a version with support before the final v1 release.

thank you @CinKon, I just came for the same reason. Awesome job.

**Comment by Coupz** [comment]
Hey @bradlc any news on the v1 betas?

**Comment by bradlc** [comment]
🎉🎉🎉 Support for v1 just shipped in `0.2.0` 🎉🎉🎉

**Comment by michaelroper** [comment]
Love your work Brad - didn't realise just how much I missed this until I got it back!
