### ISSUE TITLE
Extension causes high cpu load in Ubuntu

### ISSUE THREAD

**Issue by damvaz** [bradlc/vscode-tailwindcss#35]
- Issue Type: `Performance`
- Extension Name: `vscode-tailwindcss`
- Extension Version: `0.1.16`
- OS Version: `Linux x64 4.18.0-16-generic`
- VSCode version: `1.32.3`
- RAM: 8GB
- CPU: Intel Core i5
- Hard disk: 482,8 GB

[bradlc.vscode-tailwindcss-unresponsive.cpuprofile.txt](https://github.com/bradlc/vscode-tailwindcss/files/3003938/bradlc.vscode-tailwindcss-unresponsive.cpuprofile.txt)

**Comment by bradlc** [comment]
The extension has just received a big update and now uses a langauge server, which should improve performance a lot. Please open a new issue if you still have problems, thanks!
