### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by smitray** [bradlc/vscode-tailwindcss#38]
- Issue Type: `Performance`
- Extension Name: `vscode-tailwindcss`
- Extension Version: `0.1.16`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/smit/bradlc.vscode-tailwindcss-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bradlc** [comment]
The extension has just received a big update and now uses a langauge server, which should improve performance a lot. Please open a new issue if you still have problems, thanks!
