### ISSUE TITLE
Manually triggering autocomplete is not taking whole class name

### ISSUE THREAD

**Issue by sibbngheid** [bradlc/vscode-tailwindcss#41]
### Steps to reproduce:

- Type a class seperated with hypen.
- Back to class name with Backspace. (At this point I also expect to autocomplete opens auto.)
- Trigger autocomplete (Ctrl + Space)

Expected result:
![image](https://user-images.githubusercontent.com/19991745/56695564-0bf16900-66f2-11e9-8bc9-69d3c457c5b1.png)

Actual result:
![image](https://user-images.githubusercontent.com/19991745/56695537-01cf6a80-66f2-11e9-8b58-731f110411c8.png)

GIF:
![tail](https://user-images.githubusercontent.com/19991745/56695646-36432680-66f2-11e9-9cf3-b2819690ac10.gif)

**Comment by bradlc** [comment]
Thanks for reporting this @sibbngheid. It will be fixed in an upcoming release.

**Comment by bradlc** [comment]
Fixed in `0.2.0` 🎉
