### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Crashbits** [bradlc/vscode-tailwindcss#42]
- Issue Type: `Performance`
- Extension Name: `vscode-tailwindcss`
- Extension Version: `0.1.16`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/h/bradlc.vscode-tailwindcss-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bradlc** [comment]
The extension has just received a big update and now uses a langauge server, which should improve performance a lot. Please open a new issue if you still have problems, thanks!
