### ISSUE TITLE
Not working, I don't have any suggestions.

### ISSUE THREAD

**Issue by stefanoginella** [bradlc/vscode-tailwindcss#43]
Issue Type: <b>Bug</b>

Hi!

I have a Wordpress project, I have the project root in the Wordpress root folder, but Tailwind CSS is installed in the /wp-content/theme/theme-name/ subfolder using Yarn.

I don't have class name suggestions in any file (HTML, PHP, CSS, SCSS) and I'm not sure why. Everything else is working as expected.

Extension version: 0.1.16
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.89GB (12.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bradlc** [comment]
Hey @stefanoginella 

Some things to check:

1. Do you have a Tailwind config file and what is it’s name?
2. Does the `tailwindcss` module exist on disk? i.e. `node_modules/tailwindcss`

Is the project public by any chance?

**Comment by stefanoginella** [comment]
1. Yes, it's called `tailwind.config.js`, and the full path, relative to the root of the project is `\wp-content\themes\theme-name\resources\assets\styles\` (it's a WordPress website, and I'm using Roots Sage as a starter theme for development)
2. Yes. Again the path is` \wp-content\themes\theme-name\node_modules\tailwindcss\`

Unfortunately the project is not public.

**Comment by bradlc** [comment]
Sorry I forgot to ask which version of Tailwind as well?

**Comment by stefanoginella** [comment]
I'm using the last stable version, 0.7.4

**Comment by sibbngheid** [comment]
Try to rename your `tailwind.config.js` to `taildwind.js`. 

tailwind.config.js introduced in 1.0. Be sure your config is 0.7.4 compatible. Looks like taildwind 1.0 stable is released 1 hour ago but this extension is not yet supporting it.

Notice: tailwindcss.com is now represents 1.0 docs. To access v0 docs visit https://v0.tailwindcss.com/

**Comment by stefanoginella** [comment]
Tailwind is added automatically when configuring the WordPress Roots Sage theme during installation using composer, so the `tailwind.config.js` filename is standard with this process, even if it's an older version.

Anyway, I've tried renaming it to just `tailwind.js` and configured webpack to use it, but the extension is still not working :/

**Comment by sibbngheid** [comment]
Looks like Sage using a template engine called as blade. As I see from source code this extension supports blade templates and also handles your config file too, so keep its name as it before. 

I tested it on some blade.php files with extensions and without them. Works very well. Maybe its not working because of some your installed extensions.

Try to disable extensions about your php or blade files. If one them causes to not work, we can find a way to work with it.

Or try to install [HTML CSS Support](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css) and add this lines to your vscode settings. 
```javascript
"css.remoteStyleSheets": [
  "https://cdn.jsdelivr.net/npm/tailwindcss@0.7.4/dist/tailwind.min.css"
]
```

If it work you will get auto completions for tailwind classes from cdn. But you will not get your customizations on your tailwind.config.js and color previews for background and text color classes. If this extension is working on your project maybe maintainers can learn someting on this extension's source code.

**Comment by bradlc** [comment]
@stefanoginella please can you try with the new version of the extension, `0.2.0`?

**Comment by stefanoginella** [comment]
@bradlc Will do! I've been pretty busy this week with work and non-work related stuff, but I'll try to test it as soon as I can and I'll let you know if it works ;)

**Comment by ManuelZ** [comment]
I'm using the extension on a React project and I'm not getting any suggestions either. I'm using Tailwindcss v1

**Comment by evdama** [comment]
I'm on a svelte/sapper v3 project here, tailwind v1, and I don't get autocompletion either, not in `.html` nor in `.svelte` or `.css` files.

**Comment by bagwaa** [comment]
I had the same problem, disabled all my other extensions in the workspace and it started working, will post back if I find the culprit.

**Comment by id1385** [comment]
i installed this package and its auto fixed tanx

https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css

**Comment by Reenuay** [comment]
Hello! I have the same issue in my project. It's based on electron and vue.js. I turned off all plugins to see if it works and it's worked but only in .html file not in .vue.  I've noticed that my .vue files are recognized by vscode as a plain text so it was obvious why I'm not getting any suggestions. So I enabled back Vetur to have a .vue support and voila I've got the same issue. It stopped working even in .html files. Hope it will help.

**Comment by skycult** [comment]
Same issue for me

**Comment by bikingbadger** [comment]
Running into the same issue. Not sure how to debug the problem. Any idea's?

**Comment by bikingbadger** [comment]
I disabled all my extensions and enabled them one by one and now it's working. Not sure what to say. Wish I could help others debug what might have been the issue

**Comment by sw-yx** [comment]
thanks @bikingbadger i disabled some extensions and also got it working in html. now to make it work in jsx..

**Comment by bradlc** [comment]
Hey everyone. Now that `v0.3.0` (which has some big changes under the hood) is released, and this issue is pretty old, I am going to close it, but please open a new one if you run into any issues with that version. Remember to check the readme for the extension requirements 👍

**Comment by masifmirza927** [comment]
> This configuration worked for me on laravel blade files:
> 
> ```
> "tailwindCSS.includeLanguages": {
>     "blade": "html",
>     "php": "html",
>     "vue": "html",
>     "plaintext": "html"
>   },
> ```

that was great fix for me, i had tried a lot of things before this.
