### ISSUE TITLE
Not working when using the CDN version

### ISSUE THREAD

**Issue by fmvilas** [bradlc/vscode-tailwindcss#44]
Hi! I'm using the Tailwind CDN version so I don't have it installed as a npm package nor have a Tailwind config file. How can I make it work? Thanks!

**Comment by hacknug** [comment]
@fmvilas are you using v1.x?

**Comment by fmvilas** [comment]
Yes, following instructions on their website: https://tailwindcss.com/docs/installation#using-tailwind-via-cdn.

**Comment by bradlc** [comment]
Hey @fmvilas. Short answer is that you can’t right now. I'm not really sure how we could support this use-case in a robust way, but I am open to suggestions!

**Comment by fmvilas** [comment]
I understand. Honestly, I have no idea. Was asking in case it was just me doing something wrong 😊 . Thanks anyway!

**Comment by ilyasbabu** [comment]
3 years since this issue... Has anyone found out the solution.?

**Comment by illiyyin** [comment]
> 3 years since this issue... Has anyone found out the solution.?

this solution work for me https://stackoverflow.com/questions/71948665/tailwindcss-intellisense-in-vscode-not-working

**Comment by amanmavai** [comment]
> > 3 years since this issue... Has anyone found out the solution.?
> 
> this solution work for me https://stackoverflow.com/questions/71948665/tailwindcss-intellisense-in-vscode-not-working

This solution worked really great, Thanks man
