### ISSUE TITLE
Emmet Suggestions

### ISSUE THREAD

**Issue by spenwall** [bradlc/vscode-tailwindcss#45]
I am loving the plugin. It has really helped me writting tailwind css.

Just a thought I had was I like to write emmet abbrivations.
eg. 
```div.m-5.p-5```
Turns into
```<div class="m-5 p-5"></div>```

It would be great if while writting emmet code we could gett tailwind suggestions. I understand this might be a difficult thing to implement but I think it would be so awesome.

**Comment by bradlc** [comment]
Hey @spenwall. You can try enabling completions for Emmet-style syntax in the VS Code settings:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/2615508/57890984-a34d6600-7831-11e9-9d99-125e298b6c8a.png">

This has proven tricky to get right so it’s behind a flag for now. Let me know if you have any specific issues with it.

**Comment by spenwall** [comment]
Sorry I missed that

**Comment by BorisAnthony** [comment]
4+ years later, still behind a flag… 
I have `"tailwindCSS.emmetCompletions"` set to `true` (because this seems like a killer feature…)
But the moment I select a TW option from the drop down, Emmet "breaks" and doesn't expand the string to HTML.

Any fix on the horizon? 🙏
