### ISSUE TITLE
Completion for tw`...` is no more?

### ISSUE THREAD

**Issue by wansaleh** [bradlc/vscode-tailwindcss#46]
Hi. I just upgraded my app to Tailwind v1. Followed the migration guides to the letter. And now I'm left without autocompletion in the tw`...` (your babel plugin - babel-plugin-tailwind-components).

Can anyone give me any suggestion on how to get them back?

**Comment by bradlc** [comment]
Hey @wansaleh. This is an oversight on my part, sorry! Support for this was accidentally removed in the recent update. I will get it added back in.

**Comment by rqbazan** [comment]
> Support for this was accidentally removed in the recent update. I will get it added back in.

Hey @bradlc, what about this? 😞

**Comment by nicwhitts** [comment]
Would love this too :)

**Comment by Pytal** [comment]
> Hey @wansaleh. This is an oversight on my part, sorry! Support for this was accidentally removed in the recent update. I will get it added back in.

What's the status on this?

**Comment by bradlc** [comment]
Hey everyone. I have created a new issue (#129) to consolidate similar requests. Please refer to that issue for comments/updates
