### ISSUE TITLE
The extension is very picky on when to show suggestions

### ISSUE THREAD

**Issue by DCzajkowski** [bradlc/vscode-tailwindcss#47]
## Problem
The extension is very picky on when to show suggestions. I have recorded [a small demo](https://youtu.be/97W7UfrVq2w) reproducing the problem. When you write the class name, everything works as expected. If you delete one character at a time it also works as expected. If you remove a whole word using `alt+backspace` (in US layout the equivalent is `option+delete`) it stops showing the suggestions and it's really hard to invoke it back.

## Platform
- VS Code Version 1.34.0
- Tailwind IntelliSense version 0.2.0
- MacOS version 10.14.4

**Comment by bradlc** [comment]
Hey @DCzajkowski. Thanks for taking the time to record a video. I believe what you’re seeing is standard VS Code completion behaviour.

> [...] it's really hard to invoke it back.

You can trigger completions manually with `Ctrl+Space`. Again, this is standard behaviour. That’s the default keyboard shortcut on macOS but I’m sure you could change it if you prefer.

The only part of your video which I think is _maybe_ a little weird is at [`0:19`](https://youtu.be/97W7UfrVq2w?t=19) – I’m not 100% sure why completions aren’t showing when you start typing a fresh class name like that

**Comment by DCzajkowski** [comment]
It may be. I'll do more testing of it and compare it with standard VSCode completions ☺️

**Comment by klongmitre** [comment]
I'm having the same issue. Typing a new class name doesn't prompt the IntelliSense to show up, but the correct options show up when pressing `ctrl-space`

**Comment by SHxKM** [comment]
I'm also experiencing this (actually just finished recording a demo video). How can we help test/alleviate this? It's really counterproductive and *if* there's anything the extension can do to alter the behaviour I'll be happy to help.

**Comment by DCzajkowski** [comment]
I can confirm this is not how standard autocompletions work. `alt+backspace` removes the word, but if you start typing the pop-up appears again. I can also confirm it works as expected with Vetur, so this is not a bug with VSCode.

**Comment by ohladik** [comment]
I was also having the same issue and what helped was enabling this option in `settings.json`:
```
"editor.quickSuggestions": {
        "strings": true
      }
```
Not sure if there won't be any side effects after enabling this but so far I haven't noticed anything strange 😃

**Comment by DCzajkowski** [comment]
For me after some update to VSCode or extension it started to work flawlessly. I will close this as it seems not to be the case for me anymore and there is a solution provided by @ohladik :)
