### ISSUE TITLE
does'nt work on .vue template files ! 

### ISSUE THREAD

**Issue by sandro-git** [bradlc/vscode-tailwindcss#49]
hello, i start a project with vue cli ui and add tailwind after that the classes work but the extensions doesn't. 

you can find the test project [here](https://github.com/sandro-git/tailwind)

**Comment by bradlc** [comment]
Hey @sandro-git. The extension will only activate if your project has a [Tailwind CSS config file](https://tailwindcss.com/docs/configuration#creating-your-configuration-file).

**Comment by sandro-git** [comment]
Hello @bradlc. i forgot that sorry but after creating it with and without --full tag and reload vscode it still doesn't work. should i declare it in postcss config file to ?

**Comment by michapietsch** [comment]
Hi, came here with the same problem. Config exists and in .html it works great. But not in .vue files, and also not in .blade.php files. Do you maybe have an idea what could be the cause?

**Comment by MrSunshyne** [comment]
Same problem here. Can this be reopened ?

I have a config file. The autocomplete works, but not the syntax highlighting. Am I missing something?

![Screenshot 2019-06-10 at 17 00 25](https://user-images.githubusercontent.com/1721611/59202267-28b40400-8bad-11e9-9869-35955d3de663.png)

**Comment by natedunn** [comment]
Same issue here. I am not sure if this feature currently exists, sadly.

**Comment by afflexux** [comment]
> Same problem here. Can this be reopened ?
> 
> I have a config file. The autocomplete works, but not the syntax highlighting. Am I missing something?
> 
> ![Screenshot 2019-06-10 at 17 00 25](https://user-images.githubusercontent.com/1721611/59202267-28b40400-8bad-11e9-9869-35955d3de663.png)

Use Vetur for syntax highlighting in Vue files and use postcss as your style language.

<style lang='postcss'> ...

</style>

**Comment by rlfrahm** [comment]
I had this same problem and it didn't start working until I installed Vetur and ran through the [setup](https://vuejs.github.io/vetur/setup.html#setup).

**Comment by bhaskar-nair2** [comment]
If it helps anyone

```json
 "tailwindCSS.includeLanguages": {
    "vue": "html",
    "vue-html": "html",
  },
  ```
adding this in my settings worked for me..

**Comment by sandro-git** [comment]
> If it helps anyone
> 
> ```json
>  "tailwindCSS.includeLanguages": {
>     "vue": "html",
>     "vue-html": "html",
>   },
> ```
> 
> adding this in my settings worked for me.

can you show us the way you add it on your project ? it still doesn't work for me. I create my project with Vue CLI . how do you set up yours ?

**Comment by bhaskar-nair2** [comment]
> can you show us the way you add it on your project ? it still doesn't work for me. I create my project with Vue CLI . how do you set up yours ?

Oh no, not to your project, but to the settings in vscode.

**Comment by Elvincth** [comment]
> If it helps anyone
> 
> ```json
>  "tailwindCSS.includeLanguages": {
>     "vue": "html",
>     "vue-html": "html",
>   },
> ```
> 
> adding this in my settings worked for me..

You're the best!

**Comment by Elvincth** [comment]
> If it helps anyone
> 
> ```json
>  "tailwindCSS.includeLanguages": {
>     "vue": "html",
>     "vue-html": "html",
>   },
> ```
> 
> adding this in my settings worked for me..

@bradlc I think this should add into the default settings.

**Comment by marlongerson** [comment]
> If it helps anyone
> 
> ```json
>  "tailwindCSS.includeLanguages": {
>     "vue": "html",
>     "vue-html": "html",
>   },
> ```
> 
> adding this in my settings worked for me..

works like a charm! thank you

**Comment by DelphiWorlds** [comment]
Even after adding the includeLanguages, and using npx tailwindcss init, it still doesn't work for me

**Comment by rishabhraj291196** [comment]
> I also had to enable quick suggestions in strings to support multi-line strings. Otherwise it would only work in single-line strings. My `.vscode/settings.json` now contains the following:
> 
> ```json
> {
> 	"css.validate": false,
> 	"tailwindCSS.includeLanguages": {
> 		"vue": "html",
> 		"vue-html": "html"
> 	},
> 	"editor.quickSuggestions": {
> 		"strings": true
> 	}
> }
> ```

it works when appy this setting in setting.json

**Comment by mnik01** [comment]
For me fix was to change name of `tailwind.config.ts` to `tailwind.config.js`

**Comment by bigujun** [comment]
In my case the tailwind.config.js was in a subfolder, so i added a tailwind.config.js to the root with

`
// tailwind.config.js on root dir
module.exports = require('./frontend/tailwind.config');
`

**Comment by Alex-t-rorich** [comment]
This worked for me. Using nuxt2.

https://javascript.plainenglish.io/how-to-fix-tailwind-css-intellisense-in-visual-studio-code-3dede794df21

**Comment by phillipmohr** [comment]
My config file is called tailwind.config.ts so I had to change `"tailwindCSS.experimental.configFile": "./tailwind.config.js"` to `"tailwindCSS.experimental.configFile": "./tailwind.config.ts"`

**Comment by avxkim** [comment]
Settings.json that works for me:

```
{
  "files.associations": {
    "*.css": "tailwindcss"
  },
  "editor.quickSuggestions": {
    "strings": true
  },
  "tailwindCSS.experimental.configFile": "./tailwind.config.ts"
}
```
Thanks to @phillipmohr for figuring out when using ts config.
