### ISSUE TITLE
Autocomplete not working on literal strings

### ISSUE THREAD

**Issue by archer3cl** [bradlc/vscode-tailwindcss#50]
Say i need some variables on the prop className on React. I would want to use a es6 literal string

```jsx
<div className={`font-bold text-sm text-gray-600 hover:text-white ${className}`} />
```

The plugin doesn't show any suggestions, even with `Ctrl+Space`. But it works just fine with
```jsx
<div className="font-bold text-sm text-gray-600 hover:text-white"  />
```

**Comment by 0xNOP** [comment]
It doesn't work in both situations in my case.

![image](https://user-images.githubusercontent.com/3116731/63649681-eb3d2c80-c740-11e9-902a-d48b86b0a349.png)

**Comment by gbouteiller** [comment]
Is there any solution for that yet?  Back quotes would allow the use of the plugin on multiple lines which can be useful with many classes.

**Comment by bradlc** [comment]
Added in [`v0.3.0`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0) 🎉
