### ISSUE TITLE
Negative Margins still rely on negativeMargin key which was removed in favor of margin

### ISSUE THREAD

**Issue by mattwaler** [bradlc/vscode-tailwindcss#53]
[1.0.0-beta.6](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.0.0-beta.6) removed the negativeMargin theme key in favor of just using -m-${size} inside the margin key itself. The intellisense shows the default negative margins in the results, since it believes that you are relying on defaults without a negativeMargin key. I'm assuming this is also present in the negative inset values which were also changed in the same release.

**Comment by bradlc** [comment]
Hey @mattwaler. Sorry, I’m not 100% sure what the issue is that you’re seeing, could you explain in more detail please?

**Comment by mattwaler** [comment]
Sure, that was a horrible explanation.

It seems as though the extension is suggesting negative margin values based on an old config file key, negativeMargin, which was removed in 1.0.0-beta.6.

```
// Old tailwind.config.js

module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    negativeMargin: {
        1: '1rem',
        2: '2rem',
    },
  },
  corePlugins: {
    container: false,
  },
  plugins: [],
}
```

This key is no longer valid in the most recent version, 1.0.3, in which that key has been migrated into the standard margin key, like this.

```js
// New tailwind.config.js

module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    margin: {
        '-2': '-2rem',
        '-1': '-1rem',
        1: '1rem',
        2: '2rem',
    },
  },
  corePlugins: {
    container: false,
  },
  plugins: [],
}

```

So, when using the new valid config, the intellisense provides the default negativeMargin values when your config file lacks the negativeMargin key. So, given the above valid config file, my suggestions look like this:

![Screen Shot 2019-06-04 at 8 49 44 AM](https://user-images.githubusercontent.com/32300026/58880367-b66f8b00-86a5-11e9-87f2-256f4a8ef6bf.png)

In order to temporarily fix, I have to add the invalid negativeMargin key, with the same values, in which case the intellisense then functions properly.

```js
// Invalid patch for config

module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    margin: {
      '-2': '-2rem',
      '-1': '-1rem',
      1: '1rem',
      2: '2rem',
    },
    negativeMargin: {
      1: '1rem',
      2: '2rem',
    },
  },
  corePlugins: {
    container: false,
  },
  plugins: [],
}

```

![Screen Shot 2019-06-04 at 8 52 54 AM](https://user-images.githubusercontent.com/32300026/58880558-2e3db580-86a6-11e9-8ec7-4d393d44fb7d.png)

Hopefully this clears things up!

**Comment by bradlc** [comment]
Thanks @mattwaler, that’s much clearer!

Do you have `tailwindcss` installed in this project?

**Comment by mattwaler** [comment]
@bradlc yes, 1.0.3 is installed.

**Comment by bradlc** [comment]
I can't reproduce this, and I can't think of any reason why this would be happening.

Are you still seeing this @mattwaler?

**Comment by mattwaler** [comment]
@bradlc I am now on v1.0.5 and I am no longer seeing this issue. Maybe this was actually an issue with tailwind under the hood and it has been corrected?

**Comment by bradlc** [comment]
Yeah maybe? Honestly don't know what it could have been. Let me know if you run into it again!
