### ISSUE TITLE
Support for pug?

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [bradlc/vscode-tailwindcss#56]
Is support for pug templates planned?

**Comment by EryouHao** [comment]
+1, and support ejs?

**Comment by RayPS** [comment]
```jade
p.text-red-600.font-bold.text-6xl +1
```

**Comment by bradlc** [comment]
Pug and EJS are both supported with the `Emmet Completions` setting enabled:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/2615508/62567274-c3b21d00-b882-11e9-8120-a85e616eb18c.png">

**Comment by RayPS** [comment]
This is amazing, we appreciate everything.

**Comment by MadReal** [comment]
Is it possible to get it working inside vue file? `<template lang="pug">`

**Comment by Ruhannn** [comment]
we can use like this ;D
![image](https://github.com/user-attachments/assets/f7e75a8e-69b8-4119-a44c-6cd15cad10a5)
