### ISSUE TITLE
Not working, I don't have any auto-completion, and CSS preview

### ISSUE THREAD

**Issue by Sup3r-Us3r** [bradlc/vscode-tailwindcss#57]
#### Any idea what it might be? I have already tried reinstalling and nothing, this extension is very useful I really want to continue using.

- [X] I use the latest version of Tailwind

**Comment by bradlc** [comment]
Do you have an example of a project where it stopped working?

**Comment by Sup3r-Us3r** [comment]
### Any projects, no auto-completion :/

![Tailwindcss](https://i.ibb.co/vj8WLqS/tailwindcss.png)

**Comment by hacknug** [comment]
Not sure how this is supposed to behave when Tailwind is not installed locally and there's no config file since [the readme clearly states](https://github.com/bradlc/vscode-tailwindcss/blob/master/README.md#L11):

> Tailwind CSS IntelliSense uses your projects Tailwind installation and configuration to provide suggestions as you type.

**Comment by Sup3r-Us3r** [comment]
@hacknug Even using Tailwind locally doesn't work for me, it worked perfectly but it suddenly stopped.

**Comment by hacknug** [comment]
Have you enabled `"tailwindCSS.emmetCompletions": true`?

**Comment by Sup3r-Us3r** [comment]
Yes it's enabled.

**Comment by hawezo** [comment]
I had this issue. I can't find what causes it, but sometimes it starts working again.

**Comment by GraxMonzo** [comment]
> #### I had installed it and it works perfectly, but it stopped auto-completion, and CSS preview.
> #### Any idea what it might be? I have already tried reinstalling and nothing, this extension is very useful I really want to continue using.
> * [x]  I use the latest version of Tailwind

Can you show us your user setting.json?

**Comment by GraxMonzo** [comment]
I can help you with this problem

**Comment by Sup3r-Us3r** [comment]
Hello @GraxMonzo , thanks for your interest in helping, I really miss how this extension works, to this day it doesn't work for me anymore, if it's not too much to ask, you could maybe create a readme, with the step by step to use this extension, from the installation part of tailwindcss, if it's not too much to ask and you can help, thanks in advance!

This is my settings.json:

```
{
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "material-icon-theme",
    "window.zoomLevel": 0,
    // "editor.fontFamily": "Fira Code",
    "editor.fontSize": 14,
    "editor.lineHeight": 23,
    "editor.fontFamily": "Menlo, 'DejaVu Sans Mono', Consolas, 'Lucida Console', monospace",
    "editor.minimap.enabled": false,
    "editor.renderLineHighlight": "none",
    "workbench.colorTheme": "Punk Dark Theme",
    
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "liveServer.settings.donotShowInfoMsg": true,

    "tailwindCSS.emmetCompletions": true,
}

```

**Comment by GraxMonzo** [comment]
Try this:
1) Delete line with
`"vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",`
and
`"tailwindCSS.emmetCompletions": true,`
then save
2) Remove Tailwindcss extension
3) Reload/Reopen VSCode
4) Install Tailwindcss extension

**Comment by zadigus** [comment]
> Have you enabled this setting? `"tailwindCSS.emmetCompletions": true`

That fixed the issue for me. Thank you very much.
