### ISSUE TITLE
Not working for HTML-like files

### ISSUE THREAD

**Issue by SHxKM** [bradlc/vscode-tailwindcss#58]
Thanks for the great extension.

For regular HTML files, it works great. However, the extension stops working completely once a file is associated via VSCode to another file type.

For example, Django template files use the regular `.html` extension but include special mustache `{{ }}` syntax. I'm using another extension to get tag highlighting for these files, as well as emmet expansion. But once I associate this file as "Django HTML" - TailwindCSS Intellisense stops working.

Anything I'm missing?

**Comment by SHxKM** [comment]
Poking in the code, could it be as simple as adding "django-html" to this list in this file in [src/index.ts](https://github.com/bradlc/vscode-tailwindcss/blob/master/src/index.ts)?

```
export const HTML_LANGUAGES: string[] = [
  'blade',
  'edge',
  'ejs',
  'erb',
  'haml',
  'handlebars',
  'html',
  'HTML (Eex)',
  'jade',
  'leaf',
  'markdown',
  'njk',
  'nunjucks',
  'php',
  'razor',
  'slim',
  'svelte',
  'twig',
  'vue',
  ...JS_LANGUAGES
]
```

Perhaps it's better to make this list extensible through a setting?

**Comment by JulioBarros** [comment]
Doesn't work for me for .jsx files. Would be great if that could work too.  Thanks.

**Comment by alpap** [comment]
same here for svelte files

**Comment by dhc02** [comment]
I'm pretty sure @SHxKM's suggestion should work for django, and a similar simple change should work for most other html-like files.

As you can see from #18 , that's all it took to make this work for Phoenix last year.

I think that what we need is a setting for the extension that can be modified by users to add other filetypes so that it's not hard-coded in the extension, requiring a pull request for every addition.

This would be similar to how [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client) does it: In your `settings.json`, you can add

```javascript
"intelephense.files.associations": [
    "*.php",
    "*.phtml",
    "*.myRandomFiletype"
  ]
```

and then it will start treating `.myRandomFiletype` as php. 

I've looked into the code for this extension and I can't wrap my head around how to implement something like this yet. What do you think, @bradlc?

**Comment by rhyswat** [comment]
Ditto when I've told VS Code to treat foo.css as PostCSS. I get completions for foo.css as CSS.

Extension version 0.2.0

VS Code version 1.36.1

**Comment by ryudice** [comment]
It's not working on js and jsx files

**Comment by pavelloz** [comment]
I have the same problem, but in `.liquid` files. Maybe it would be nice to just have an option that you place under a language that enables plugin.

ie.

```
    "[html]": {
        "tailwindcss.enabled": true
    },
```

**Comment by skycult** [comment]
It does not works for any Vue + Tailwind project.

**Comment by pavelloz** [comment]
BTW. @skycult make sure you have config file in your project.

When i was tuning forked extension for my use case i discovered https://github.com/bradlc/vscode-tailwindcss/blob/master/package.json#L25-L27 which means extension wont even activate until you have a tailwind config.

**Comment by kamalhm** [comment]
@pavelloz 

I've added the tailwind config but it still doesnt show up on vue-file, any suggestion?

**Comment by reducio** [comment]
I have problem with `.html.eex` and `.html.leex` files in Phoenix (Elixir).

If changing the VSCode file type (lower right hand corner of window) to HTML manually when editing tailwind classes which is annoying but does work.

So I can see this extension support HTML (EEx): https://github.com/bradlc/vscode-tailwindcss/blob/f5dfe02f74ac9bd68529f1997ae875691b819833/src/index.ts#L50

Check topic on the ElixirForum, please: https://elixirforum.com/t/how-to-force-the-tailwind-css-intellisense-extension-for-vscode-work-with-html-eex-and-html-leex-files/25520

**Comment by reducio** [comment]
> I have problem with `.html.eex` and `.html.leex` files in Phoenix (Elixir).
> 
> If changing the VSCode file type (lower right hand corner of window) to HTML manually when editing tailwind classes which is annoying but does work.
> 
> So I can see this extension support HTML (EEx):
> 
> https://github.com/bradlc/vscode-tailwindcss/blob/f5dfe02f74ac9bd68529f1997ae875691b819833/src/index.ts#L50
> 
> Check topic on the ElixirForum, please: https://elixirforum.com/t/how-to-force-the-tailwind-css-intellisense-extension-for-vscode-work-with-html-eex-and-html-leex-files/25520

Solution: https://elixirforum.com/t/how-to-force-the-tailwind-css-intellisense-extension-for-vscode-work-with-html-eex-and-html-leex-files/25520/4?u=stavanger

**Comment by ben-foster** [comment]
Here's a workaround I found for .js and .jsx files. Probably works for other file types:

![tailwind suggestions](https://user-images.githubusercontent.com/16801663/65734765-890a7b00-e0a2-11e9-8a4c-47aafde46c60.gif)

**Comment by jrock2004** [comment]
It would be awesome of we could add our list of filetypes because I think it would be bad for the maintainer of the plugin to have to add them all. The real logic seems to be in `tailwindcss-language-server` which seems to be private. Would be awesome to hear from main developer on if he would like help implementing something or are we all stuck with the ext he has chosen?

**Comment by claudio10** [comment]
Need to use the extension for .cfm files too.

**Comment by mrmurphy** [comment]
I'd love to have it work for `.re` files!

**Comment by flaugher** [comment]
For what it's worth, I switched to Intellisense for CSS by Zignd and it works for my use case which is setting the VS Code language mode to Django HTML.

**Comment by SolarisFlare** [comment]
I would love to see this work on **.NET** files (`.razor` - Razor Syntax)!

**Comment by angieherrera** [comment]
Would love this for .twig files as well.

**Comment by fpauser** [comment]
And I'd love to see support for glimmer templates (hbs) in Ember.js projects

**Comment by joshchernoff** [comment]
I personally like how emmet does it.

```
  "emmet.includeLanguages": {
    "HTML (Eex)": "html",
    "HTML (EEx)": "html",
  },
```

though from reading the code not sure why #54 is not working.

**Comment by bux** [comment]
👍 for mustache files

**Comment by dasAnderl** [comment]
doesnt work in vue files in vs code. does work in intellij idea though.

**Comment by zolrath** [comment]
I can confirm that while trying the new v`0.3.0-alpha.1` vsix the extension fails to provide IntelliSense for "HTML (EEx)" (`.html.eex` and `.html.leex`) files.

Testing on standard `.html` files in the same directory provides IntelliSense so it's not deactivated for this project as a whole, just the EEx files.

**Comment by bradlc** [comment]
@zolrath That's odd. It works fine for me in `.html.eex` files with [this extension](https://marketplace.visualstudio.com/items?itemName=mjmcloug.vscode-elixir) installed. Are you using the same one?

I am definitely going to look into adding a file association setting 👍 For now I have added some languages to [`v0.3.0-alpha-1`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.1) so please let me know if I've missed yours

**Comment by bux** [comment]
@bradlc 
adding `*.mustache` would be appreciated

**Comment by zolrath** [comment]
> 
> 
> @zolrath That's odd. It works fine for me in `.html.eex` files with [this extension](https://marketplace.visualstudio.com/items?itemName=mjmcloug.vscode-elixir) installed. Are you using the same one?
> 
> I am definitely going to look into adding a file association setting 👍 For now I have added some languages to [`v0.3.0-alpha-1`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.1) so please let me know if I've missed yours

I am using the [ElixirLS extension](https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls) which is the current most-supported Elixir plugin.
I tried the extension you linked, both with ElixirLS enabled and with ElixirLS disabled and I not getting IntelliSense on `.html.eex` files.

**Comment by joshchernoff** [comment]
I also get the same ^

**Comment by zolrath** [comment]
I've been performing some tests for Elixir support now that the name is correct.

In a standard Phoenix project the directory structure (only showing relevant files/folders) is:
```
./
├── assets
│   └── node_modules
│   └── tailwind.config.js
├── lib
│   └── example_web
│   │   └── templates
│   │   │   └── layout (or any folder name)
│   │   │   │   └── root.html.eex
│   │   │   │   └── live.html.leex
│   │   └── live
│   │   │   └── page_live.html.leex
│   │   │   └── collocated_live.ex (this contains a render function with the html inside it)
```

The behavior I'm seeing is that if I start VSCode in the root directory I get no Tailwind IntelliSense of any kind.

**Start VSCode in root**

- No IntelliSense in `html`
- No IntelliSense in `html.eex` or `html.leex`

**Start VSCode in /assets**

- Immediate IntelliSense on `.html` files
- IntelliSense must be manually triggered. If I type Ctrl+Space I get IntelliSense in `html.eex` or `html.leex` files.  It does not automatically trigger while typing but once Ctrl+Space or a space is pressed it begins autocompleting. If backspace is pressed autocomplete stops and must be retriggered with Ctrl+Space.


It seems that the extension isn't recognizing the tailwind.config.js files location?

**Comment by mikebusby** [comment]
Would love to see support for nunjucks templates (.njk)

**Comment by gerrywastaken** [comment]
Use this instead: https://marketplace.visualstudio.com/items?itemName=Atishay-Jain.All-Autocomplete

Just open the generated css file (e.g. public/css/app.css) in a tab and the classes will complete in all other tabs.

**Comment by lobo-tuerto** [comment]
> I personally like how emmet does it.
> 
> ```
>   "emmet.includeLanguages": {
>     "HTML (Eex)": "html",
>     "HTML (EEx)": "html",
>   },
> ```
> 
> though from reading the code not sure why #54 is not working.

For anyone stumbling upon this, the new way for making emmet work with your `.html.eex` files now is:

```js
"emmet.includeLanguages": {
  "html-eex": "html"
},
```

**Comment by Nisthar** [comment]
any updates?

**Comment by bradlc** [comment]
`django-html` is now one of the languages with built-in support 👍

**Comment by andreasRu** [comment]
So this issue "not working for HTML like files" has been closed with addition of django-html support? Should I open another issue for adding the support for other html like file extensions that still won't work, or should we just forget about it for now?

> @zolrath That's odd. It works fine for me in `.html.eex` files with [this extension](https://marketplace.visualstudio.com/items?itemName=mjmcloug.vscode-elixir) installed. Are you using the same one?
> 
> I am definitely going to look into adding a file association setting  For now I have added some languages to [`v0.3.0-alpha-1`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.1) so please let me know if I've missed yours

**Comment by bradlc** [comment]
@andreasRu [`v0.3.0`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0) added support for any language, via the `includeLanguages` setting. If it's not working for you please open a new issue.

**Comment by andreasRu** [comment]
@bradlc Oh goodness!!! Just updated/added to my workplace, works PERFECTLY!!! LOVE YOU 💯 THANK YOU SO MUCH!!!

**Comment by imbwaldo** [comment]
Thanks a ton, Brad!

**Comment by icarthik** [comment]
could you pls extend for .hbs handlebars files

**Comment by icarthik** [comment]
@bradlc could you pls extend for .hbs handlebars files

**Comment by jd-0001** [comment]
for hbs:

```json
{
    "tailwindCSS.includeLanguages": {
        "hbs": "html",
    },
}

```

**Comment by stoqe** [comment]
- this still doesn't seem to work for nunjucks
- should it?
- nunjucks is so gooooood

**Comment by xshapira** [comment]
For Django templates:
```bash
"tailwindCSS.includeLanguages": {
    "plaintext": "django-html",
    "django-html": "html",
  }
```

Works flawlessly!

**Comment by koppel** [comment]
Thanks for that!  The same works for nunjucks; can we make this part of the documentation?

```
    "tailwindCSS.includeLanguages": {
        "plaintext": "njk",
        "njk": "html"
    }
```

**Comment by JexPY** [comment]
@xshapira  thnx,

Worked in the custom workspace:

```JSON
    "json.schemaDownload.enable": true,
    "files.associations": {
        "*.html": "jinja-html"
    },
    "emmet.includeLanguages": {
        "jinja-html": "html"
    },
    "[jinja-html]": {
        "editor.defaultFormatter": "monosans.djlint",
        "editor.detectIndentation": false,
        "editor.tabSize": 2,
        "editor.formatOnSave": true
    },
    "tailwindCSS.includeLanguages": {
        "plaintext": "jinja-html",
        "jinja-html": "html",
        "javascript": "javascript",
        "css": "css"
    }
  ```

**Comment by IgorArnaut** [comment]
> For Django templates:
> 
> "tailwindCSS.includeLanguages": {
>     "plaintext": "django-html",
>     "django-html": "html",
>   }
> 
> Works flawlessly!

Doesn't work for me. I ahve both Tailwind CSS Intellisense and junstyle's Django Template Support.

**Comment by IgorArnaut** [comment]
> [@andreasRu](https://github.com/andreasRu) [`v0.3.0`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0) added support for any language, via the `includeLanguages` setting. If it's not working for you please open a new issue.

How do I set it for .jsx files?
