### ISSUE TITLE
Suggestions Do Not Work on Occasion 

### ISSUE THREAD

**Issue by smhmd** [bradlc/vscode-tailwindcss#59]
Could you fix tailwind intellisense to work with non-html tags in Pug as well as not having to explicit when having a div with an id.

![tTH1Q6gIT2](https://user-images.githubusercontent.com/46059092/62416141-46419f00-b62d-11e9-91e1-91a93f5dfcb0.gif)

**Comment by lucas1619** [comment]
i have the same problem, have you found the answer?

**Comment by smhmd** [comment]
@lucas1619 No, this repo is slightly abandoned. I just learned to live with it. :cry:

**Comment by bradlc** [comment]
This feature has been revamped in [`v0.3.0`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0) and should be much better now
