### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by benface** [bradlc/vscode-tailwindcss#6]
First of all, thank you so much for this.

It would be cool if not only the linter didn't mark Tailwind's "additions" to CSS as invalid (for instance it doesn't like `@apply .some-class`, complaining with `[css] identifier expected`), but to go one step further and highlight `@apply` and the utilities following it. Similarly, `config()` could be highlighted the same way other CSS "functions" such as `calc()` are.

I don't know if that's possible, but if it is, it would make this awesome extension even better. :) Thanks!

EDIT: I forgot to mention `@tailwind` and `@screen`.

**Comment by benface** [comment]
> I use this extension and then set VS Code to associate CSS files with PostCSS: "files.associations": { "*.css": "postcss" } If you do that it won’t complain about the syntax you mentioned.

Hmm, I don't think that's gonna work for me, as I'm also using Sass (.scss files) with Tailwind.

No big deal. Thank you for your quick response :)

**Comment by bradlc** [comment]
Okay so I misspoke earlier 😅

You _can_ actually do this.

**Before:**
<img width="337" alt="image" src="https://user-images.githubusercontent.com/2615508/44737787-d9ec2080-aaea-11e8-8e51-81fbf25a2c8a.png">

**After:**
<img width="337" alt="image" src="https://user-images.githubusercontent.com/2615508/44737837-f25c3b00-aaea-11e8-8681-ca4d6b13b0f4.png">

**Comment by bradlc** [comment]
Although, after some digging I still can’t find a way around the **validation** issue.

If you require validation I would recommend disabling the built-in validation, and using [stylelint](https://stylelint.io/) instead, which allows [defining custom at-rules](https://stylelint.io/user-guide/rules/at-rule-no-unknown/).

In terms of syntax highlighting.. how do you imagine the class names after an `@apply` looking?

**Comment by bradlc** [comment]
**Before:**
<img width="345" alt="image" src="https://user-images.githubusercontent.com/2615508/44740655-ed02ee80-aaf2-11e8-8d3e-1075e0801fd7.png">

**After:**
<img width="345" alt="image" src="https://user-images.githubusercontent.com/2615508/44740606-cba20280-aaf2-11e8-92b8-42adbfe54c61.png">

What do you think?

**Comment by benface** [comment]
Looks perfect! :)

**Comment by bradlc** [comment]
Sweet! This is released now so let me know if you run in to any issues :)

**Comment by benface** [comment]
Re-closing this, everything seems to work well :) Thanks again
