### ISSUE TITLE
Support for TailwindCSS v.1

### ISSUE THREAD

**Issue by Klieger** [bradlc/vscode-tailwindcss#60]
Possible to update this extension to the recent v.1 release of TailwindCSS?

**Comment by hacknug** [comment]
Tailwind v1.x support was added in v0.2.0 of the plugin: https://github.com/bradlc/vscode-tailwindcss/issues/34#issuecomment-493235664

**Comment by bradlc** [comment]
@Klieger As @hacknug said, v1 is supported. Please open a new issue if you are still having problems.
