### ISSUE TITLE
Double suggetsions?

### ISSUE THREAD

**Issue by cannikin** [bradlc/vscode-tailwindcss#62]
Any idea what's causing this? I get two suggestions for each CSS property, one will have the color preview and one not:

![image](https://user-images.githubusercontent.com/300/63536739-0bfb4d00-c4c9-11e9-8d58-f4f09b79e1b7.png)

In that case each one is right after the other but sometimes there are whole blocks of the non-color version:

![image](https://user-images.githubusercontent.com/300/63536778-27665800-c4c9-11e9-8f03-4e8d9cd5d1fc.png)

And then the working color swatches all bunched up later:

![image](https://user-images.githubusercontent.com/300/63536811-39e09180-c4c9-11e9-8a96-3d62f4a1e54e.png)

This is a super-simple test project so far, no crazy config:

```
// package.json
{
  "name": "workcation",
  "version": "1.0.0",
  "description": "Tailwind demo",
  "main": "index.js",
  "scripts": {
    "build": "postcss css/tailwind.css -o public/build/tailwind.css"
  },
  "author": "Rob Cameron",
  "license": "MIT",
  "private": false,
  "dependencies": {
    "autoprefixer": "^9.6.1",
    "postcss-cli": "^6.1.3",
    "tailwindcss": "^1.1.2"
  }
}

// tailwind.config.js
module.exports = {
  theme: {
    extend: {}
  },
  variants: {},
  plugins: []
}
```

**Comment by hacknug** [comment]
Are you using _IntelliSense for CSS class names in HTML_ by any chance? I think the ones without color are coming from that extension (have it disabled on my computer for some reason so…)

**Comment by cannikin** [comment]
@hacknug Oh snap that fixed it, thanks!

**Comment by tyler36** [comment]
```HTML CSS Support``` was causing duplicate entries for me
