### ISSUE TITLE
Not working in Vue SFC

### ISSUE THREAD

**Issue by mgesmundo** [bradlc/vscode-tailwindcss#63]
Hi,
I tried to use with Vue SFC 2.6.10 and Tailwind 1.1.2 but it does not works. I use also Vetur 0.22.2 
Any suggestion?
All the best.

**Comment by Nasser-allah** [comment]
Try adding this extension, it may fix it.
https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css

**Comment by sebastienbarre** [comment]
Really strange, sometimes it's working for me, sometimes it's not. I added the "HTML CSS Support",  no change...

**Comment by bahung1221** [comment]
I facing same problem, and now i made it working by manually trigger vscode suggestion.

see [#76](https://github.com/bradlc/vscode-tailwindcss/issues/76#issuecomment-538294128)

**Comment by hacknug** [comment]
Have you tried adding this to your settings? `"tailwindCSS.emmetCompletions": true`

**Comment by mgesmundo** [comment]
Thank you @hacknug! Now it works!
