### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by praveenperera** [bradlc/vscode-tailwindcss#64]
Can you release an updated version of this extensions its the latest commits please?

**Comment by garth** [comment]
Spent some time hacking the plugin code in my vscode packages folder to get this plugin working. When I forked to repo to make a PR, was surprised to find that the fix has already been applied but not released.

**Comment by bradlc** [comment]
[`v0.3.0`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0) is available in the marketplace now 🎉
