### ISSUE TITLE
Code for `tailwindcss-language-server` available?

### ISSUE THREAD

**Issue by praveenperera** [bradlc/vscode-tailwindcss#65]
Hey is the code for `'tailwindcss-language-server'` from `server.ts` 

`import 'tailwindcss-language-server'`

Because I had to go into node_modules and manually edit the minified `tailwindcss-language-server` file to get autocomplete working with #54

**Comment by praveenperera** [comment]
I added the uglified version into the repo, and I was able to make changes in it. Its hacky but works.

https://github.com/praveenperera/vscode-tailwindcss/commit/b284170dc120f8268536d065f1e6f45239b838de

**Comment by jrock2004** [comment]
@praveenperera even though you added the file, I still need to go into the `node_modules/tailwindcss-language-server` to update the minifed file to add new file types to support

**Comment by webdeb** [comment]
@bradlc whats the reason to hide "tailwindcss-language-server"?

**Comment by bradlc** [comment]
Really sorry for the delay on this. The code is now available on the `next` branch
