### ISSUE TITLE
Does this extension support SCSS files?

### ISSUE THREAD

**Issue by codeams** [bradlc/vscode-tailwindcss#69]
I'm getting errors when using apply inside SCSS files.

SCSS:
![image](https://user-images.githubusercontent.com/5368213/64916072-693a9500-d73b-11e9-831a-59badfa3e11a.png)

CSS:
![image](https://user-images.githubusercontent.com/5368213/64916068-5758f200-d73b-11e9-99dc-191ae196dfaa.png)

**Comment by sleeyax** [comment]
@codeams how did you fix this??

**Comment by markkoo** [comment]
@codeams how did you fix this??

**Comment by ShaneYu** [comment]
Just for completion, you might want to include the following at directive also:

```json
{
      "name": "@layer",
      "description": "Use the @layer directive to tell Tailwind which “bucket” a set of custom styles belong to. Valid layers are base, components, and utilities.",
      "references": [
        {
          "name": "Tailwind Documentation",
          "url": "https://tailwindcss.com/docs/functions-and-directives#layer"
        }
      ]
    }
```
