### ISSUE TITLE
@screen autocomplete

### ISSUE THREAD

**Issue by benface** [bradlc/vscode-tailwindcss#7]
Second feature request from me. :)

It would be awesome to get the same kind of autocomplete that we get with `@apply` but with Tailwind's `@screen` directive. It would list all the screens defined in the Tailwind config.

Thanks again!

**Comment by bradlc** [comment]
How’s this? Added in `0.1.9`

![kapture 2018-08-28 at 13 09 52](https://user-images.githubusercontent.com/2615508/44722179-325bf780-aac4-11e8-9e68-ed2f172a7a4a.gif)

**Comment by benface** [comment]
Awesome! So quick, thank you very much!
