### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SylvanoTombo** [bradlc/vscode-tailwindcss#70]
Hey there,
I'm unable to get it working. In my case, my tailwind.config.js is in the root project and I'm using it in vuejs project and it just doesn't seem to be doing anything. I don't see any autocomplete popup when typing class names.

**Comment by SylvanoTombo** [comment]
I have to install this plugin (HTML CSS Support) to get it working.

**Comment by mathew3** [comment]
@SylvanoTombo thanks, worked. This should be pinned or included in docs @bradlc
