### ISSUE TITLE
Doesn't work for TSX files

### ISSUE THREAD

**Issue by arimendelow** [bradlc/vscode-tailwindcss#72]
When using TypeScript with React, this plugin doesn't work. How can I configure it to look at .tsx files?

**Comment by lednhatkhanh** [comment]
How did you solve this?

**Comment by or2008** [comment]
just installed and it doesn't work for me, lets see if this comment fixes it :)

**Comment by Manubi** [comment]
doesn't work for me either in .tsx only if I write "class" instead of "className" I get the autosuggest...

**Comment by arimendelow** [comment]
That's weird, it should work without any configuration. I'm still unsure why it didn't for me initially.

**Comment by sw-yx** [comment]
same - it didnt work on tsx originally, then i panicked and clicked around and now it works

**Comment by bentruyman** [comment]
I also ran into this. Not sure if it's anything TSX-related (but it was failing in TSX files for me). But to fix it I simply created a `tailwind.config.js` file in my project.

```js
module.exports = {
  theme: {},
  variants: {},
  plugins: [],
};
```

It seems [a config file](https://github.com/bradlc/vscode-tailwindcss/blob/f5dfe02f74ac9bd68529f1997ae875691b819833/src/index.ts#L24) is what enables this extension in a project.

**Comment by exoer** [comment]
In vscode - extensions - Tailwin CSS Intellisense. Click on the settings button ("manage"). 

Find Tailwind CSS - Include languages 
Click 'edit in settings.json'

add 
`
  "tailwindCSS.includeLanguages": {      
    "plaintext": "javascript"
  }
`

**Comment by b-groeneveld** [comment]
I've added 

```"tailwindCSS.includeLanguages": { "typescriptreact": "html" },```

And restarted vscode and it was good to go

**Comment by oxyian-dev** [comment]
> I've added
> 
> `"tailwindCSS.includeLanguages": { "typescriptreact": "html" },`
> 
> And restarted vscode and it was good to go

Super its working for me

**Comment by khalidahmada** [comment]
You can add this in user settings

`"tailwindCSS.includeLanguages": {
    "typescript": "javascript",
    "typescriptreact": "javascript"
}`

**Comment by miko1991** [comment]
doesnt work with custom webpack babel typescript react

**Comment by avxkim** [comment]
@khalidahmada this what it made work for me in Nuxt 3 + TS

**Comment by paulwongx** [comment]
> You can add this in user settings
> 
> `"tailwindCSS.includeLanguages": { "typescript": "javascript", "typescriptreact": "javascript" }`

@khalidahmada 
Can you explain what this is doing? Someone above suggested ` "typescriptreact": "html"` Why `typescriptreact: "javascript"`?

**Comment by Manubi** [comment]
> > You can add this in user settings
> > `"tailwindCSS.includeLanguages": { "typescript": "javascript", "typescriptreact": "javascript" }`
> 
> @khalidahmada Can you explain what this is doing? Someone above suggested ` "typescriptreact": "html"` Why `typescriptreact: "javascript"`?

You can find more information here: 
[json](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/4b215ba92eb2b0ac0043328468adb10a5b118bfd/packages/vscode-tailwindcss/CHANGELOG.md#L348)

[markdownDescription](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/4b215ba92eb2b0ac0043328468adb10a5b118bfd/packages/vscode-tailwindcss/package.json#L142)

[This setting allows you to add additional language support. The key of each entry is the new language ID and the value is any one of the extensions [built-in languages](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/tailwindcss-language-service/src/util/languages.ts), depending on how you want the new language to be treated (e.g. `html`, `css`, or `javascript`):](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/4b215ba92eb2b0ac0043328468adb10a5b118bfd/packages/vscode-tailwindcss/README.md#L61-L62)

**Comment by hamzatalha77** [comment]
just go to tailwind.config.js and add tsx in the model like this:
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
}
and will works for you ^^

**Comment by arsalanmohseni** [comment]
Use this:
```json
"tailwindCSS.includeLanguages": {
        "typescriptreact": "html",
        "javascriptreact": "html"
 }
```
