### ISSUE TITLE
Suggestion: add to README.md that you need tailwind.config.js for plugin to work

### ISSUE THREAD

**Issue by kouliavtsev** [bradlc/vscode-tailwindcss#74]
Thanks for the awesome plugin! ⚡️

The `npx tailwind init` is optional if you read the Tailwind CSS docs. It is a bit confusing if you skip that step, install the Tailwind CSS IntelliSense plugin, and autocomplete does not work. 

In other words, it took me some time to figure this out. 😅 It would be great to mention this somewhere in the docs, so that other people would not waste time on this.

**Comment by khaneda09** [comment]
I created a GitHub account just to thank you @kouliavtsev ... I was trying to make the plugin work with no luck and I luckily ran into your post. Thanks again!

And thanks @bradlc for this great plugin!

**Comment by ZediWards** [comment]
@kouliavtsev Just to add. I installed Tailwind with npm and am building my output css with the command `npm run build:css`. This has to be ran again if you ran it before you ran `npx tailwind init`
Snippet from my package.json file:
```
"scripts": {
    "build:css": "tailwind build src/style.css -o dist/style.css"
  },
```

**Comment by jacobkball** [comment]
Yes, something in the Readme file about how Tailwind is required to be installed would be most helpful!

**Comment by surjithctly** [comment]
Can someone merge this pull request. It will definitely help newbies like me.
