### ISSUE TITLE
Extension not working for simple html and php files

### ISSUE THREAD

**Issue by Salman9000** [bradlc/vscode-tailwindcss#75]
I installed the tailwindcss extension in vscode, just like how the readme says, but it is not working. Any idea why is this issue coming up?
![image](https://user-images.githubusercontent.com/26120951/66138515-312ac180-e618-11e9-9c03-266e95239764.png)

**Comment by bahung1221** [comment]
I facing same problem, and now i made it working by install [html-css-support plugin](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css) and then manually trigger vscode suggestion by `ctrl + space` shortcut.

see [#76](https://github.com/bradlc/vscode-tailwindcss/issues/76#issuecomment-538294128)

**Comment by hacknug** [comment]
Have you tried adding this to your settings? `"tailwindCSS.emmetCompletions": true`

**Comment by lateek35** [comment]
Same here, I tried to add `"tailwindCSS.emmetCompletions": true` to my settings, but still no completion.

**Comment by lateek35** [comment]
Update on this,

Despite my multiple tries and restart of vscode yesterday nothing worked. I didn't do anything more on this point since, however vscode ask me for an update today, now its working fine, what a pleasure!
So for my case, that definitely wasn't an issue related to vscode-tailwind plugin.

**Comment by gabrielfojo** [comment]
I had the same problem with gulp, after creating the file tailwind.config.js the problem is solved.

**Comment by ycs77** [comment]
I have the same problem. It used to work, but it doesn't work now.

OS: Win10
vscode-tailwindcss version: 0.2.0

**Comment by Sarokhezer** [comment]
Same problem here. i added "tailwindCSS.emmetCompletions": true and tried everything mentioned here and in the other "issues"... but to no avail. 
VS 1.42.1 
OS: Win10
i'm using: "https://unpkg.com/browse/tailwindcss@1.2.0/dist/tailwind.min.css"

**Comment by Sarokhezer** [comment]
> Same problem here. i added "tailwindCSS.emmetCompletions": true and tried everything mentioned here and in the other "issues"... but to no avail.
> VS 1.42.1
> OS: Win10
> i'm using: "https://unpkg.com/browse/tailwindcss@1.2.0/dist/tailwind.min.css"

ok... i'm kinda new to all of this VS and tailwind thing but i tried some things and was able to make it right.
i installed tailwind with "npm install tailwindcss" in ConEmu 
and then moved my index.html file to the folder of ConEmu  
it worked... idk why? 
i tried some moving and stuff... when i have the folder "node_modules" (that is originaly in ConEmu's folder), in the same folder with my .html file, the extension works... 
is there anyway for the extenstion to work even when the .html file and the ConEmu are in a separate folder?

**Comment by manprajapat** [comment]
> I facing same problem, and now i made it working by install [html-css-support plugin](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css) and then manually trigger vscode suggestion by `ctrl + space` shortcut.
> 
> see [#76](https://github.com/bradlc/vscode-tailwindcss/issues/76#issuecomment-538294128)

Works for me!! :)

**Comment by bradlc** [comment]
@Salman9000 Hey, did you manage to get the extension working? If not please could you share your project structure, ideally in a GitHub repo if possible?

**Comment by Salman9000** [comment]
> @Salman9000 Hey, did you manage to get the extension working? If not please could you share your project structure, ideally in a GitHub repo if possible?

The extension is not working. Here is my repo link https://gitlab.com/salmanhanif133/game-store

**Comment by bradlc** [comment]
It is because you have multiple config files. It works for me in your project if I either (1) open the `newfrontend` folder in VS Code, or (2) delete `frontend/tailwind.config.js` and open the root directory in VS Code

Multiple config files is something that doesn't really work right now. Trying to think of the best way to handle that.

**Comment by Salman9000** [comment]
> It is because you have multiple config files. It works for me in your project if I either (1) open the `newfrontend` folder in VS Code, or (2) delete `frontend/tailwind.config.js` and open the root directory in VS Code
> 
> Multiple config files is something that doesn't really work right now. Trying to think of the best way to handle that.

Okay i Deleted my frontend folder, reinstalled tailwindcss extension and now it works. Thanks for the help! Cheers!
