### ISSUE TITLE
Only working on existed tag, new tag not working (both .vue and plain .html)

### ISSUE THREAD

**Issue by bahung1221** [bradlc/vscode-tailwindcss#76]
I facing an issue after installed vscode-tailwindcss,

It doesn't show any suggestion if my cursor is on an new html tag, but it work fine on existed tag that already use tailwind, sorry for my bad english, please see images below for more information.

<img width="1440" alt="existed-tag" src="https://user-images.githubusercontent.com/27690861/66180830-ab028f80-e698-11e9-995c-cb067ff9c555.png">
<img width="1440" alt="new tag" src="https://user-images.githubusercontent.com/27690861/66180838-b2299d80-e698-11e9-9fc1-d03c48822f90.png">

Additional, sometime it show suggestion after i typed a tailwind class, example `<div class="mr-5 "`, but sometime it doesn't show anything

Should i need to install any other extensions to get it working correctly?

Thank you for great work!

**Comment by bahung1221** [comment]
Find it out, i must manually trigger suggestion by `ctrl + space` shortcut.
Is it an issue of vscode or this extension?

**Comment by hacknug** [comment]
Did you try adding this to your settings? `"tailwindCSS.emmetCompletions": true`

**Comment by bahung1221** [comment]
i added `"tailwindCSS.emmetCompletions": true` into user setting, but i still must manual trigger suggestion by  `ctrl + space` shortcut

**Comment by hacknug** [comment]
Even after reloading the window or restarting the app?

**Comment by bahung1221** [comment]
yes, i even restarted my mac,

additional, i'm using latest vscode (downloaded yesterday), `vscode-tailwindcss` version 0.2.0 and latest [IntelliSense for CSS class names in HTML](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion) (i also tried [HTML CSS Support](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css))

This may not an issue of `vscode-tailwindcss`, maybe `HTML CSS Support` issue. I just wondering how you made it work in your machine, are you need to add any extra extensions?

**Comment by thelittlebug** [comment]
i had exactly the same issue with vscode on linux.
after adding
```json
"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
},
```
to my vscode settings everything work as expected.

**Comment by bahung1221** [comment]
Thank you very much @thelittlebug 😄 ,
but it still not working on my mac, i think i will try to upgrade macos and reinstall vscode later.
