### ISSUE TITLE
Non-indented rule break syntax highlighting

### ISSUE THREAD

**Issue by gio00** [bradlc/vscode-tailwindcss#79]
Hi, 

as you can see from the image:
![image](https://user-images.githubusercontent.com/7753563/66703093-18ed2d80-ed0f-11e9-8394-84a39ed82423.png)

Normal indented rule works but non indented one break syntax highlighting.

**Comment by bradlc** [comment]
Thanks for flagging this! Highlighting should be fixed now in [`v0.3.0-alpha.1`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.1)

**Comment by bradlc** [comment]
[`v0.3.0`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0) is available in the marketplace now 🎉
