### ISSUE TITLE
No CSS preview while typing classes (in HTML and CSS)

### ISSUE THREAD

**Issue by benface** [bradlc/vscode-tailwindcss#8]
I am looking at the animated screenshots in the extension's description, and I see that as you're typing Tailwind classes in HTML or in CSS (following `@apply`) you see the corresponding CSS declaration next to the highlighted class in the IntelliSense popup. It doesn't work for me though:

<img width="464" alt="no-css" src="https://user-images.githubusercontent.com/1059139/44673369-4dae0080-a9f9-11e8-868f-34a7676e2b9d.png">

<img width="434" alt="no-css-2" src="https://user-images.githubusercontent.com/1059139/44673370-4f77c400-a9f9-11e8-8fc4-bc0c9b5e4d4d.png">

I should see `background-attachment: fixed;` next to `bg-fixed`, but there's nothing there.

**Comment by bradlc** [comment]
Huh, that’s odd. I’ve never seen that before. Do you have any VS Code settings enabled that might be hiding the detail?

**Comment by benface** [comment]
No, it's pretty much a brand new install of VS Code. I just reloaded it and now it works. Weird, I had reloaded after installing the extension... oh well :P Thanks for the quick response!
