### ISSUE TITLE
Error occurs when disabling a default colour

### ISSUE THREAD

**Issue by lewishowles** [bradlc/vscode-tailwindcss#80]
I'm working on my first project using Tailwind as intended, and found your extension really useful as I can never remember the class names.

After tweaking my Tailwind config, I noticed the intellisense stopped working. After much head-scratching, I noticed the following code breaks the autocompletion - presumably because it's expecting the `gray` colours to exist.

```javascript
const { colors } = require('tailwindcss/defaultTheme');

module.exports = {
  theme: {
    extend: {
      colors: {
        // Use the appropriate spelling for grey
        gray: false,

        grey: {
          ...colors.gray,
        },
      },
    },
  },
};
```

and comes up with the following error in the output console:
```
Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot convert undefined or null to object
  Code: -32603 
```

**Comment by hacknug** [comment]
This should solve it `gray: {},`

**Comment by lewishowles** [comment]
That seems to do the trick! Thank you.
