### ISSUE TITLE
Suggestions only pop up when typing at the end of a class string

### ISSUE THREAD

**Issue by lukepighetti** [bradlc/vscode-tailwindcss#81]
<img width="853" alt="Screen Shot 2019-10-25 at 2 07 36 PM" src="https://user-images.githubusercontent.com/666539/67593756-e260db00-f730-11e9-8929-63ec19b560e4.png">
<img width="858" alt="Screen Shot 2019-10-25 at 2 08 05 PM" src="https://user-images.githubusercontent.com/666539/67593755-e260db00-f730-11e9-92e6-bb7fc24cc6ab.png">

reproduce:

Create two spaces followed by one space
```
<div class="bg-red-600  | text-left">
```

Delete a space, type `upper` cannot autocomplete
```
<div class="bg-red-600 upper| text-left">
```

**Comment by dixonge** [comment]
This also occurs when you leave the window. You have to backspace over anything you have typed, then hit space for the preview to pop up

**Comment by bradlc** [comment]
[`v0.3.0`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0) has just been released and I can't reproduce this issue in that version. Please let me know if you're still seeing this issue though.
