### ISSUE TITLE
Feature request: color non-recognized styles differently

### ISSUE THREAD

**Issue by chadananda** [bradlc/vscode-tailwindcss#85]
I waste a lot of time trying to figure out why things are not working only to (much) later realize that I'd fat-fingered a class name or used a size which is not defined. 

I would love it is the non-recognized classes could be colored differently so I could see at a glance those that I probably typed wrong.

**Comment by bradlc** [comment]
Hey @chadananda. Thanks for the feature request.

I think this is outside the scope of this extension to be honest. I would imagine that most people using Tailwind are using it with some additional custom CSS, and I wouldn't want the extension to highlight **valid** class names from outside Tailwind.

I am open to suggestions as to how something like this could work with that in mind though.

**Comment by bradlc** [comment]
I think for now it is outside the scope of the extension. We only know about Tailwind-generated class names so we can't effectively highlight unknown class names without inadvertently highlighting class names that _do_ exist outside of Tailwind.
