### ISSUE TITLE
Not working in rails project (.erb files)

### ISSUE THREAD

**Issue by laurosilvacom** [bradlc/vscode-tailwindcss#87]
I can't seem to activate it inside a rails project that uses .erb files. I tried adding these settings to my VScode config file but no luck: 

```
{
  "files.associations": {
    "*.html.erb": "erb"
  },
  "emmet.includeLanguages": {
    "html.erb": "html",
    "erb": "html"
  }
}
```

Any suggestions?

**Comment by pavelloz** [comment]
>     "*.html.erb": "erb"
Set this to 
>     "*.html.erb": "html"

And it will work, hopefully you dont have too much ruby in your views, because that wont be highlighted anymore.

**Comment by laurosilvacom** [comment]
That worked! Thanks for the help @pavelloz

**Comment by andyjeffries** [comment]
Is there any future solution to allow this within HTML ERB files properly (rather than losing the ERB highlighting and functionality)? I'd *LOVE* to use this, but really can't give up the ERB highlighting for it.

**Comment by andyjeffries** [comment]
I've just seen in https://github.com/bradlc/vscode-tailwindcss/blob/master/src/index.ts#L45 that ERB should be supported? It's not working for me at the moment.

**Comment by andyjeffries** [comment]
Actually weirdly, I've tried switching the language of a file to HTML and it still didn't work, but the extension is installed and not disabled. Any ideas?

**Comment by andyjeffries** [comment]
Never mind, just seen https://github.com/bradlc/vscode-tailwindcss/issues/100
