### ISSUE TITLE
tailwindcss-language-server debug log conflicting with vim-lsc

### ISSUE THREAD

**Issue by mikepjb** [bradlc/vscode-tailwindcss#91]
Hi Brad,

I've been using the underlying language server for this plugin using vim-lsc (see raised issue here: https://github.com/natebosch/vim-lsc/pull/251)

There is a call to `console.log(t.configDependencies)` that is causing a `[]` to be prepended to the message header being sent. This prevents `tailwindcss-language-server` being used.

It'd be good to understand why that log is there, if it's not useful could you remove it from the npm library?

Best,
Mike

**Comment by mikepjb** [comment]
Bumping this, any chance we can sort something out?

Let me know if there's anything I can do to help :+1:

**Comment by bradlc** [comment]
All logs have been removed in [`v0.3.0`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0), which is available now
