### ISSUE TITLE
Enable Support for Template Strings

### ISSUE THREAD

**Issue by EyMaddis** [bradlc/vscode-tailwindcss#93]
Hi,
This extension is awesome, thanks for your work!
However, a minor thing bugs me which is that template literals do not work, e.g. 

```js
className={`m-2`}
```

**Comment by kentcdodds** [comment]
Any direction on where to start to look into this? I'm guessing this is actually an issue that needs to be fixed in the `tailwindcss-language-server` but that's [an odd module](https://unpkg.com/browse/tailwindcss-language-server@0.0.1/)...

**Comment by kingdaro** [comment]
[It seems like that's where we're stuck.](https://github.com/bradlc/vscode-tailwindcss/issues/95) Issues aren't being answered and PRs aren't being accepted. It's looking like we'll need to recreate this project

**Comment by bradlc** [comment]
This is supported in [`v0.3.0-alpha.1`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.1) – check it out if you get chance 🙂
