### ISSUE TITLE
intellisense not working for devcontainer with python3 (django) and tailwind

### ISSUE THREAD

**Issue by elmcrest** [bradlc/vscode-tailwindcss#94]
hey everybody. I try to setup intellisense for tailwind, as many others here do.

1. I've build a `.vsix` file from a cloned repo to get the freshest version of this plugin
2. I've tried to follow all settings I could find

if you'd like to try it yourself, checkout [my repo](https://github.com/elmcrest/mehr-handwerkde) if you like. if `remote development extension` and `docker` is installed on your machine, vscode will ask you to `reopen in devcontainer` and do the rest.
after installation you need to manually install the vsix file with the Command Viewlet thing (for me it's `cmd + shift + p` and `Install from VSIX`

any hints appreciated - also if you tell me what information I could provide to debug this.

thx in advance,
elmcrest

**Comment by elmcrest** [comment]
ok I got it working without the most downloaded `django` extension for vscode. No Idea though how to debug this, same behavior for custom build or version from "extension store".

**Comment by bradlc** [comment]
Hey @elmcrest. I'm curious if you've tried the newest version of the extension, and whether that fixes the issue you were having?

**Comment by elmcrest** [comment]
hey @bradlc,

Yeah it‘s been a while, but somehow I got it working. can‘t provide any details right now but I‘ll try to remember within the next days.

**Comment by elmcrest** [comment]
hey @bradlc,

sorry I can‘t tell you right away. Maybe just close the issue?
I probably won’t have much time the next days.

**Comment by bradlc** [comment]
I'll close it if that's ok with you, but definitely feel free to open a new one if you run into any other problems!
