### ISSUE TITLE
Any chance you could open source tailwindcss-language-server?

### ISSUE THREAD

**Issue by tadeaspetak** [bradlc/vscode-tailwindcss#95]
Hey! This plugin was working fabulously until about two weeks back (possibly malfunctioning now due to an update to a newer tailwind version, but not sure) — I've been trying to figure out what happened, but since I can't access the source of the `tailwindcss-language-server`, there's not that much I can do apart from verifying that the client the `vscode` extension runs (which it does).

Any chance you could open source tailwindcss-language-server? Heaps of cheers in advance, would love to keep this plugin going 💪

**Comment by w3bdesign** [comment]
@bradlc Any chance for this to happen?

**Comment by dylanirlbeck** [comment]
Not sure if this would be helpful, but it's possible the language server can be found here: https://github.com/iamcco/coc-tailwindcss/tree/master/lsp/tailwindcss-language-server.

`coc-tailwindcss` is a Vim extension to provide a similar functionality to this plugin, so the language server might be useful (if it's not the same!).

**Comment by bradlc** [comment]
Really sorry for the delay on this. The code is now available on the `next` branch
