### ISSUE TITLE
IntelliSense not working from HTML file

### ISSUE THREAD

**Issue by ycs77** [bradlc/vscode-tailwindcss#97]
It used to work normally, but now it doesn't work anymore, there is no IntelliSense prompt in HTML.

**Comment by erolabzait** [comment]
@ycs77 Do you have Tailwindcss in your node_modules?

**Comment by ycs77** [comment]
@erolabzait Yes, installed local and global.

**Comment by ycs77** [comment]
Solved after adding tailwind.config.js, reference to https://github.com/bradlc/vscode-tailwindcss/issues/75#issuecomment-565131939.
