### ISSUE TITLE
Support for tailwind-rn would be great!

### ISSUE THREAD

**Issue by vgrafe** [bradlc/vscode-tailwindcss#99]
Hi!

There's now [tailwind-rn](https://github.com/vadimdemedes/tailwind-rn) that allows React Native devs to use tailwind to style their apps. It would be great to have the same level of intellisense delivered when in a RN environment.

I wish I could help but I am quite busy right now, so maybe someone can work on a PR around this.

**Comment by bradlc** [comment]
Hey @vgrafe. Thank you for the suggestion!

I am not sure what to do about this to be honest. I am reluctant to add support for anything that isn't "official." (That includes things like `tailwind.macro`)

I am considering some sort of setting which would allow you to add custom regular expressions to match against, although I'm not sure how well that would work. What do you think about that?

**Comment by vgrafe** [comment]
I understand and agree with your approach. Great job on putting `vscode-tailwindcss` together by the way, it is so helpful!

**Comment by bradlc** [comment]
Hey @vgrafe. I have created a new issue (#129) to consolidate similar requests. Please refer to that issue for comments/updates
